# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='admin', max_length=200)),
                ('admin_password', models.CharField(default='5f4dcc3b5aa765d61d8327deb882cf99', max_length=200)),
                ('admin_id', models.CharField(default='Test', max_length=200)),
            ],
        ),
    ]
