# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SampleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='time_delta',
            field=models.DecimalField(decimal_places=8, default=0.5, max_digits=12),
        ),
    ]
